# Generated by Django 5.1.15 on 2026-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Custom meta description. Fallback to excerpt if blank.', max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom HTML title tag. Fallback to article title if blank.', max_length=255),
        ),
    ]
