# Generated by Django 5.1.15 on 2026-08-27 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(db_index=True, default='general', help_text='Category group e.g., general, academy, admissions', max_length=100)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['category'], name='pages_faq_categor_14afa9_idx'), models.Index(fields=['is_active'], name='pages_faq_is_acti_634241_idx'), models.Index(fields=['sort_order'], name='pages_faq_sort_or_068e0d_idx')],
            },
        ),
    ]
