# Generated by Django 5.1.15 on 2026-08-27 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('school', 'School'), ('university', 'University'), ('ngo', 'NGO'), ('government', 'Government'), ('company', 'Company'), ('other', 'Other')], default='school', max_length=20)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('area_of_interest', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'School Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('program', 'Program'), ('event', 'Event'), ('school', 'School'), ('partnership', 'Partnership'), ('other', 'Other')], db_index=True, default='general', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam'), ('archived', 'Archived')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inquiries_i_status_8fae14_idx'), models.Index(fields=['type'], name='inquiries_i_type_ed589c_idx'), models.Index(fields=['created_at'], name='inquiries_i_created_225eb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_name', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=255)),
                ('student_age', models.PositiveIntegerField(blank=True, null=True)),
                ('student_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('preferred_schedule', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='programs.program')),
            ],
            options={
                'verbose_name_plural': 'Program Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
